// SPDX-License-Identifier: MIT
/**
 * hosts.mjs 单源同步脚本（date-wrapper 模式）。
 *
 * - 默认：**校验** package.json / dsh.plugin.json / README 与 hosts.mjs 一致，
 *   有漂移则列出差异并以退出码 1 失败（CI 用）。
 * - `--write`：把 supportedHosts 枚举回写四处 ——
 *   1. package.json peerDependencies（dshPeers 五包 = 枚举 OR-list）
 *   2. package.json engines.dsh（同一 OR-list；loader 预检门与安装门必须同源）
 *   3. package.json devDependencies（devHostDeps 钉 developmentHost 精确版）
 *   4. dsh.plugin.json engines.dsh + README.md / README.en.md 兼容句
 *
 * 生成块由标记注释包裹，脚本只改标记内的内容：
 *   <!-- hosts-sync:begin --> … <!-- hosts-sync:end -->
 */
import { readFileSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'
import { dshPeers, devHostDeps, developmentHost, peerRange, supportedHosts } from './hosts.mjs'

const HERE = dirname(fileURLToPath(import.meta.url))
const ROOT = join(HERE, '..')
const WRITE = process.argv.includes('--write')
const RANGE = peerRange()

const BEGIN = '<!-- hosts-sync:begin -->'
const END = '<!-- hosts-sync:end -->'

const failures = []

function editJson(path, mutate, label) {
  const before = readFileSync(path, 'utf8')
  const doc = JSON.parse(before)
  mutate(doc)
  const after = JSON.stringify(doc, null, 2) + '\n'
  if (before === after) return
  if (!WRITE) failures.push(`${label}: 与 hosts.mjs 不同步（跑 node scripts/sync-hosts.mjs --write）`)
  else writeFileSync(path, after)
}

/** 包体 README / 清单 README 的兼容节（标记内，允许幂等重写）。 */
function compatBlock(lang) {
  if (lang === 'zh') {
    return `${BEGIN}
<!-- 由 scripts/sync-hosts.mjs 生成，勿手改；单源在 scripts/hosts.mjs -->
支持 DSH ${supportedHosts.join('、')}（枚举 peer，逐 rc 实测白名单；alpha/beta 不在支持范围）。
${END}`
  }
  return `${BEGIN}
<!-- Generated by scripts/sync-hosts.mjs; single source in scripts/hosts.mjs -->
Supports DSH ${supportedHosts.join(', ')} (enumerated peers — a per-rc tested whitelist; alpha/beta releases are out of scope).
${END}`
}

/** 把标记块插入 markdown（有则整体替换，无则插到第一个二级标题前，兜底追加到尾部）。 */
function upsertCompat(path, block, label) {
  let text
  try { text = readFileSync(path, 'utf8') } catch { return }
  const start = text.indexOf(BEGIN)
  if (start >= 0) {
    const end = text.indexOf(END, start)
    if (end < 0) { failures.push(`${label}: 存在 ${BEGIN} 但缺少 ${END}`); return }
    const next = text.slice(0, start) + block + text.slice(end + END.length)
    if (next !== text) {
      if (!WRITE) failures.push(`${label}: 兼容节与 hosts.mjs 不同步`)
      else writeFileSync(path, next)
    }
    return
  }
  const heading = /\n## /m.exec(text)
  const withBlock = `\n${block}\n`
  const next = heading !== null
    ? text.slice(0, heading.index) + withBlock + text.slice(heading.index + 1)
    : text.replace(/\s*$/, `\n${block}\n`)
  if (!WRITE) failures.push(`${label}: 缺少兼容节`)
  else writeFileSync(path, next)
}

// 1+2+3. package.json：peers / engines / devDeps
editJson(join(ROOT, 'package.json'), (pkg) => {
  for (const name of dshPeers) pkg.peerDependencies[name] = RANGE
  pkg.engines ??= {}
  pkg.engines.dsh = RANGE
  for (const [name, version] of Object.entries(devHostDeps())) {
    pkg.devDependencies ??= {}
    if (name in pkg.devDependencies) pkg.devDependencies[name] = version
  }
}, 'package.json')

// 4a. dsh.plugin.json
editJson(join(ROOT, 'dsh.plugin.json'), (m) => {
  m.engines ??= {}
  m.engines.dsh = RANGE
}, 'dsh.plugin.json')

// 4b. README 兼容节（zh + en）
upsertCompat(join(ROOT, 'README.md'), compatBlock('zh'), 'README.md')
upsertCompat(join(ROOT, 'README.en.md'), compatBlock('en'), 'README.en.md')

if (failures.length > 0) {
  console.error(`hosts-sync: ${failures.length} 处漂移`)
  for (const f of failures) console.error(`  - ${f}`)
  process.exit(1)
}
console.log(`hosts-sync: ${WRITE ? 'written' : 'ok'} — ${supportedHosts.length} hosts, dev=${developmentHost}`)
